export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR';
export const REQUEST_PRODUCTS_IN_PROCESS = 'REQUEST_PRODUCTS_IN_PROCESS';
